### PR TITLE
Updated validator

### PR DESCRIPTION
**Pull request by ThomasLuca**

### CODE REVIEW

**Review by thomascrmbz — COMMENTED** [review]
Looks good, will approve when the sanboxing workflow is installed (tomorrow)

**Comment by DimDim2001** [comment]
DeviceToBackend validation and backend must be updated too to handle the newest JSON schema version. I think battery object is moved inside a voltage object.
Make sure everything will still work when merging.
Decodedpayload in TTN must be changed manually, so let us know when needed.

**Comment by thomascrmbz** [comment]
And this is exactly why I didn't merge yet.

**Comment by ThomasLuca** [comment]
New commit updated the DeviceToBackend. I also changed schema in the backend  [[updated json-schema #9 ](https://github.com/vives-projectwerk-2021/pulu-backend/pull/9)]

**Review by thomascrmbz — APPROVED** [review]

**Pull request merged**
